trigger:
  - master

stages:
- stage: Build
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      name: iModelTechCI
      demands:
      - Cmd

    variables:
      bbSrcRoot: $(Agent.BuildDirectory)/bbsrc
      bbStream: bim0200
      buildStrategy: BisSchemasPackaging
      architecture: x64
      verbosity: 6
      system.debug: true

    steps:
      - checkout: self
        clean: true
      - task: PythonScript@0
        displayName: Setup Environment
        inputs:
          scriptSource: inline
          script: |
            import os, sys
            def set_vsts_env(key, value): print(key + ' = ' + value + '\n##vso[task.setvariable variable={0}]{1}'.format(key, value))
            
            set_vsts_env('PYTHONUNBUFFERED', '1')
            set_vsts_env('BsiSrc', os.environ['bbSrcRoot'].replace('/', os.path.sep) + os.path.sep)
            set_vsts_env('BsiOut', os.environ['BUILD_BINARIESDIRECTORY'] + os.path.sep)

      - task: bentleybootstrap@0
        displayName: BentleyBootstrap
        inputs:
          streamname: '$(bbStream)'
          srcroot: '$(bbSrcRoot)'

      - task: PythonScript@0
        displayName: 'Link Repo'
        inputs:
          scriptSource: inline
          script: |
            import os, sys
            
            if os.name == 'nt':
                import win32file
                def createDirLink(target, link):
                    win32file.CreateSymbolicLink(link, target, 1)
            elif os.name == 'posix':
                def createDirLink(target, link):
                    os.symlink(target, link)
            else:
                sys.stderr.write('Unknown OS name "' + os.name + '".\n')
                sys.exit(-1)
            
            link = os.path.join(sys.argv[1], 'BisSchemas')
            target = os.environ['BUILD_SOURCESDIRECTORY']
            if not os.path.exists(link):
                createDirLink(target, link)

          arguments: '$(bbSrcRoot)'

      - task: BatchScript@1
        displayName: 'Shared Shell'
        inputs:
          filename: '$(bbSrcRoot)\bsicommon\shell\SharedShellEnv.bat'
          modifyEnvironment: true

      - script: bb -v$(verbosity) -s $(buildStrategy) -a $(architecture) pull
        displayName: bb pull

      - script: bb -v$(verbosity) -s $(buildStrategy) -a $(architecture) build --tmrbuild --noprompt
        displayName: bb build

      # - task: PublishPipelineArtifact@1
      #   inputs:
      #     path: $(BsiOut)\Winx64\packages
      #     artifact: bis-schemas-packages
      - publish: $(BsiOut)\Winx64\packages
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'

- stage: Publish_Packages
  displayName: Publish Packages
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: publish_ProGet
    displayName: Publish npm packages to ProGet
    steps:
      - checkout: none
      - download: current
        artifact: bis-schemas-packages
      - task: Npm@1
        displayName: 'Publish Core'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Core'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish Standard'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Standard'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish Grids'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Grids'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish Structural'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Structural'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish RealityModeling'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/RealityModeling'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish RoadRailAlignment'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/RoadRailAlignment'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish RoadRailPhysical'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/RoadRailPhysical'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish ClassificationSystems'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/ClassificationSystems'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish SpatialComposition'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/SpatialComposition'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish BuildingSpatial'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/BuildingSpatial'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish ECObjects'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/ECObjects'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
      - task: Npm@1
        displayName: 'Publish Earthwork'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Earthwork'
          verbose: false
          publishEndpoint: 'ProGet npm.bentley.com publish token'
