trigger:
  - master

stages:
- stage: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      name: iModelTechCI
      demands:
      - Cmd

    workspace:
      clean: all
    variables:
    - group: 
    - name: pkgOut
      value: '$(Agent.BuildDirectory)/Packages'

    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.16.0'
        inputs:
          versionSpec: 12.16.0
      - checkout: self
        clean: true

      #Your build pipeline references a secret variable named ‘’. This variable is pulled from the '' variable group.  You must authorize this build to use that group: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group
      - powershell: |
          $npmrcDir = "$(Build.Repository.LocalPath)"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=/"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:username=Packages" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:_password=$()" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:email=npm requires email to be set but doesn't use the value" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:username=Packages" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:_password=$()" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:email=npm requires email to be set but doesn't use the value" -Append

        displayName: 'Seed npmrc'
        
      - script: npm install
        displayName: 'npm install'

      # Temporarily specify --alwaysGen for initial publish to public npmsjs.
      - script: node ./tools/packages/generatePackages.js --inventory ./SchemaInventory.json --skipList ./ignoreSchemaList.json --outDir $(pkgOut) --template ./tools/packages/package.json.template --alwaysGen
        displayName: Generate Packages

      - publish: $(pkgOut)
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'

- stage: Publish_Packages_Internal
  displayName: Publish Internal Packages
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/publish-npmjs'),  ne(variables['skipInternal'], true))
  jobs:
  - job: PublishInternal
    displayName: Publish npm packages to Azure Artifacts
    variables:
      - group: 
    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        displayName: 'Use Node 10.15.0'
        inputs:
          versionSpec: 10.15.0
      - download: current
        artifact: bis-schemas-packages
      
      #Your build pipeline references a secret variable named ‘’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
      - bash: |
          npm config set @bentley:registry /
          
          npm config set ////_packaging/Packages/npm/registry/:username=
          npm config set ////_packaging/Packages/npm/registry/:_password=$()
          npm config set ////_packaging/Packages/npm/registry/:email="not used"
          npm config set ////_packaging/Packages/npm/:username=
          npm config set ////_packaging/Packages/npm/:_password=$()
          npm config set ////_packaging/Packages/npm/:email="not used"
        displayName: 'Seed npmrc'

      - script: npm install
        displayName: 'npm install'
          
       #- script: node ./tools/packages/publishPackages.js --packages $(Pipeline.Workspace)/bis-schemas-packages --isRealRun
      - script: node ./tools/packages/publishPackages.js --packages $(Pipeline.Workspace)/bis-schemas-packages
        displayName: Publish packages

- stage: Publish_Packages_External
  displayName: Publish Public Packages
  dependsOn: Publish_Packages_Internal
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/publish-npmjs'),  ne(variables['skipExternal'], true))
  jobs:
  - job: PublishExternal
    displayName: Publish npm packages to npmjs
    variables:
      - group: 
      - group: ""
    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        displayName: 'Use Node 10.15.0'
        inputs:
          versionSpec: 10.15.0
      - download: current
        artifact: bis-schemas-packages

      #Your build pipeline references a secret variable named ‘’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
      - bash: |
          npm config set @bentley:registry /
          
          npm config set ////_packaging/Packages/npm/registry/:username=
          npm config set ////_packaging/Packages/npm/registry/:_password=$()
          npm config set ////_packaging/Packages/npm/registry/:email="not used"
          npm config set ////_packaging/Packages/npm/:username=
          npm config set ////_packaging/Packages/npm/:_password=$()
          npm config set ////_packaging/Packages/npm/:email="not used"
        displayName: 'Seed npmrc'

      - script: npm install
        displayName: 'npm install'

      - bash: |
          
          npm config set //registry.npmjs.org/:_authToken=$(artifactsToken)
          
          
        displayName: 'Seed npmrc'
      
      - script: node ./tools/packages/publishPackages.js --packages $(Pipeline.Workspace)/bis-schemas-packages --public --isRealRun
        displayName: Publish packages
