trigger:
  - master

stages:
- stage: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      name: 
      demands:
      - Cmd

    variables:
      pkgOut: $(Agent.BuildDirectory)/Packages

    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.15.0'
        inputs:
          versionSpec: 10.15.0
      - checkout: self
        clean: true


      - powershell: |
          $npmrcDir = "$(Build.Repository.LocalPath)"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=/"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:username=Packages" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:_password=$()" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:email=npm requires email to be set but doesn't use the value" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:username=Packages" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:_password=$()" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:email=npm requires email to be set but doesn't use the value" -Append


      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: install
      - script: |
          SET PYENV_NAME=pyenv

          virtualenv %PYENV_NAME%

          $(System.DefaultWorkingDirectory)\pyenv\Scripts\pip.exe install python-ntlm
          $(System.DefaultWorkingDirectory)\pyenv\Scripts\pip.exe install pywin32==224
          $(System.DefaultWorkingDirectory)\pyenv\Scripts\pip.exe install lxml

        displayName: 'Setup python environment'
      - script: $(System.DefaultWorkingDirectory)\pyenv\Scripts\python.exe tools/signoff/signoff.py --getLaunchCodes --dumpjson
        displayName: Get Launch codes (temp)
      - script: node ./tools/packages/generateInventory.js --BisRoot .
        displayName: Build Schema Inventory (temp)
      - script: node ./tools/packages/generatePackages.js --inventory ./SchemaInventory.json --outDir $(pkgOut) --template ./tools/packages/package.json.template --skipBetaPackages
        displayName: Generate Packages (no beta packages)

      - publish: $(pkgOut)
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'

- stage: Publish_Packages
  displayName: Publish Packages
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: publish

    steps:
      - checkout: self
      - task: NodeTool@0
        displayName: 'Use Node 10.15.0'
        inputs:
          versionSpec: 10.15.0
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: install
      - download: current
        artifact: bis-schemas-packages

 (dry run)
