trigger:
  - master

pr:
  drafts: false
  branches:
    include:
      - master
  paths:
    include:
      - tools/packages/

stages:
- stage: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      name: 
      demands:
      - Cmd

    workspace:
      clean: all
    variables:
    - group: 
    - name: pkgOut
      value: '$(Agent.BuildDirectory)/Packages'

    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.16.0'
        inputs:
          versionSpec: 12.16.0
      - checkout: self
        clean: true

      
      - powershell: |
          $npmrcDir = "$(Build.Repository.LocalPath)"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=https://registry.npmjs.org/"


        
      - script: npm install
        displayName: 'npm install'

      # Temporarily specify --alwaysGen for initial publish to public npmsjs.
      - script: node ./tools/packages/generatePackages.js --inventory ./SchemaInventory.json --skipList ./ignoreSchemaList.json --outDir $(pkgOut) --template ./tools/packages/package.json.template
        displayName: Generate Packages

      - publish: $(pkgOut)
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'

- stage: Publish
  displayName: Publish
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'),  ne(variables['skipInternal'], true))
  jobs:
  - job: Publish

    variables:
 
    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        displayName: 'Use Node 10.15.0'
        inputs:
          versionSpec: 10.15.0
      - download: current
        artifact: bis-schemas-packages

      - script: npm install
        displayName: 'npm install'


      - bash: |
          
          
          

          
          
   
          





- stage: Publish
  displayName: Publish
  dependsOn: Publish
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'),  ne(variables['skipExternal'], true))
  jobs:
  - job: Publish
    displayName: Publish
    variables:
 ""
    steps:
      - checkout: self
        clean: true
      - task: NodeTool@0
        displayName: 'Use Node 10.15.0'
        inputs:
          versionSpec: 10.15.0
      - download: current
        artifact: bis-schemas-packages

      - bash: |
          

          
          


      - script: npm install
        displayName: 'npm install'



