trigger:
  - master

pr:
  drafts: false
  branches:
    include:
      - master
  paths:
    include:
      - tools/packages/

stages:
- stage: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      name: iModelTechCI
      demands:
      - Cmd

    workspace:
      clean: all
    variables:
    - name: pkgOut
      value: '$(Agent.BuildDirectory)/Packages'

    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.16.0'
        inputs:
          versionSpec: 12.16.0
      - checkout: self
        clean: true

      #Your build pipeline references a secret variable named ‘artifactsRegistryToken’. This variable is pulled from the 'arzure-artifacts-npm-token' variable group.  You must authorize this build to use that group: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group
      - powershell: |
          $npmrcDir = "$(Build.Repository.LocalPath)"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=https://registry.npmjs.org/"

        displayName: 'Seed npmrc'
        
      - script: npm install
        displayName: 'npm install'

      # Temporarily specify --alwaysGen for initial publish to public npmsjs.
      - script: node ./tools/packages/generatePackages.js --inventory ./SchemaInventory.json --skipList ./ignoreSchemaList.json --outDir $(pkgOut) --template ./tools/packages/package.json.template
        displayName: Generate Packages

      - publish: $(pkgOut)
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'
