trigger:
  - master

stages:
- stage: Build
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      name: 
      demands:
      - Cmd

    variables:
      bbSrcRoot: $(Agent.BuildDirectory)/bbsrc
      bbStream: imodel02
      buildStrategy: BisSchemasPackaging
      architecture: x64
      verbosity: 6
      system.debug: true

    steps:
      - checkout: self
        clean: true
      - task: PythonScript@0
        displayName: Setup Environment
        inputs:
          scriptSource: inline
          script: |
            import os, sys
            def set_vsts_env(key, value): print(key + ' = ' + value + '\n##vso[task.setvariable variable={0}]{1}'.format(key, value))
            
            set_vsts_env('PYTHONUNBUFFERED', '1')
            set_vsts_env('BsiSrc', os.environ['bbSrcRoot'].replace('/', os.path.sep) + os.path.sep)
            set_vsts_env('BsiOut', os.environ['BUILD_BINARIESDIRECTORY'] + os.path.sep)

      - task: bentleybootstrap@0
        displayName: BentleyBootstrap
        inputs:
          streamname: '$(bbStream)'
          srcroot: '$(bbSrcRoot)'

      - task: PythonScript@0
        displayName: 'Link Repo'
        inputs:
          scriptSource: inline
          script: |
            import os, sys
            
            if os.name == 'nt':
                import win32file
                def createDirLink(target, link):
                    win32file.CreateSymbolicLink(link, target, 1)
            elif os.name == 'posix':
                def createDirLink(target, link):
                    os.symlink(target, link)
            else:
                sys.stderr.write('Unknown OS name "' + os.name + '".\n')
                sys.exit(-1)
            
            link = os.path.join(sys.argv[1], 'BisSchemas')
            target = os.environ['BUILD_SOURCESDIRECTORY']
            if not os.path.exists(link):
                createDirLink(target, link)

          arguments: '$(bbSrcRoot)'

      - task: BatchScript@1
        displayName: 'Shared Shell'
        inputs:
          filename: '$(bbSrcRoot)\bsicommon\shell\SharedShellEnv.bat'
          modifyEnvironment: true

      - script: bb -v$(verbosity) -s $(buildStrategy) -a $(architecture) pull
        displayName: bb pull


      - powershell: |
          $npmrcDir = "$(bbSrcRoot)/BisSchemas"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=/"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:username=Packages" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:_password=$()" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/registry/:email=npm requires email to be set but doesn't use the value" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:username=Packages" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:_password=$()" -Append
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "////_packaging/Packages/npm/:email=npm requires email to be set but doesn't use the value" -Append


      - script: bb -v$(verbosity) -s $(buildStrategy) -a $(architecture) build --tmrbuild --noprompt
        displayName: bb build

      - publish: $(BsiOut)\Winx64\packages
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'

- stage: Publish_Packages
  displayName: Publish Packages
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: publish

    steps:
      - checkout: none
      - download: current
        artifact: bis-schemas-packages
      - task: Npm@1
        displayName: 'Publish Core Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Core'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish Standard Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Standard'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish Grids Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Grids'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish Structural Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/StructuralPhysical'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish RealityModeling Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/RealityModeling'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish RoadRailAlignment Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/RoadRailAlignment'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish RoadRailPhysical Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/RoadRailPhysical'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish ClassificationSystems Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/ClassificationSystems'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish SpatialComposition Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/SpatialComposition'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish BuildingSpatial Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/BuildingSpatial'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish ECObjects Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/ECObjects'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish Earthwork Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Earthwork'
          publishRegistry: useFeed
          publishFeed: Packages
      - task: Npm@1
        displayName: 'Publish Construction Azure Artifact'
        inputs:
          command: publish
          workingDir: '$(Pipeline.Workspace)/bis-schemas-packages/Construction'
          publishRegistry: useFeed
          publishFeed: Packages
