trigger:
  - master

pr:
  drafts: false
  branches:
    include:
      - master
  # paths:
  #   include:
  #     - tools/packages/

stages:
- stage: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: build_packages
    displayName: Build Packages
    pool:
      vmImage: windows-latest

    workspace:
      clean: all
    variables:
    - name: pkgOut
      value: '$(Agent.BuildDirectory)/Packages'

    steps:
      - task: NodeTool@0
        displayName: 'Use Node 14.16.0'
        inputs:
          versionSpec: 14.16.0
      - checkout: self
        clean: true

      - powershell: |
          $npmrcDir = "$(Build.Repository.LocalPath)"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=https://registry.npmjs.org/"

        displayName: 'Seed npmrc'
        
      - script: npm install
        displayName: 'npm install'

      # Temporarily specify --alwaysGen for initial publish to public npmsjs.
      - script: node ./tools/packages/generatePackages.js --inventory ./SchemaInventory.json --skipList ./ignoreSchemaList.json --outDir $(pkgOut) --template ./tools/packages/package.json.template
        displayName: Generate Packages

      - publish: $(pkgOut)
        artifact: bis-schemas-packages
        displayName: 'Publish Pipeline Artifact'

- stage: Generate
  dependsOn: []
  jobs:
  - job: generate_jsons
    displayName: Generate JSONS
    pool:
      vmImage: windows-latest

    workspace:
      clean: all
    variables:
    - name: jsonOut
      value: '$(Agent.BuildDirectory)/JSONS'
    - name: zipOut
      value: '$(Agent.BuildDirectory)/schemaJSONS.zip'
    
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 14.16.0'
        inputs:
          versionSpec: 14.16.0
      - checkout: self
        clean: true
      
      - powershell: |
          $npmrcDir = "$(Build.Repository.LocalPath)"
          
          if(!(Test-Path -Path $npmrcDir)){
              mkdir $npmrcDir
          }
          
          $npmrcFile = $npmrcDir + "/.npmrc"
          
          Out-File -FilePath $npmrcFile -Encoding ascii -InputObject "@bentley:registry=https://registry.npmjs.org/"

          if(!(Test-Path -Path $jsonOut)){
              mkdir $jsonOut
          }

        displayName: 'Seed npmrc'
        
      - script: npm install
        displayName: 'npm install'
      
      - script: node ./tools/packages/getSchemaJsons.js --latestReleasedVersions --OutDir $(jsonOut)
        displayName: Generate Jsons 
      - task: ArchiveFiles@2
        displayName: Compress json files into zip
        inputs:
          rootFolderOrFile: '$(jsonOut)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(zipOut)'
      - publish: $(zipOut)
        artifact: bis-schemas-jsons
        displayName: 'Publish Pipeline Artifact'