trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Domains/Core
      - Standard

pr:
  drafts: false
  branches:
    include:
      - master
  # paths:
  #   include:
  #     - Domains/Core
  #     - Standard
  #   exclude:
  #     - Domains/Core/media

jobs:
- job: iModelEvolutionTests
  workspace:
    clean: all

  pool:
    name: iModelTechCI
    demands: Agent.OS -equals Windows_NT

  variables:
    srcRoot: $(Agent.BuildDirectory)/bbsrc/
    outRoot: $(Build.BinariesDirectory)/
    buildStrategy: 'iModelEvolutionTests;buildall'
    verbosity: '4'
    architecture: 'x64'
    language: 'en'

  steps:
  - checkout: self
    clean: true

  - task: bentleysystemsinternal.bentley-build-tasks.bentleybootstrap.bentleybootstrap@0
    displayName: 'BentleyBootstrap imodel02'
    inputs:
      streamname: 'imodel02'
      srcroot: $(srcRoot)

  - task: bentleysystemsinternal.bentley-build-tasks.bentleybuild.bentleybuild@1
    displayName: 'bb pull'
    inputs:
      command: 'pull'
      strategy: $(buildStrategy)
      linkRepoToSrcRoot: false
      verbosity: $(verbosity)
      architecture: $(architecture)
      language: $(language)
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

  - script: |
      cd $(Agent.BuildDirectory)/bbsrc/BisSchemas
      git checkout %SYSTEM_PULLREQUEST_SOURCEBRANCH:refs/heads/=%
      git branch
    displayName: 'Set source branch'

  - task: bentleysystemsinternal.bentley-build-tasks.bentleybuild.bentleybuild@1
    displayName: 'bb build'
    inputs:
      command: build
      strategy: $(buildStrategy)
      useLocalizedDir: false
      verbosity: $(verbosity)
      architecture: $(architecture)
      language: $(language)
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
