trigger:
  - master

pr:
  drafts: false
  branches:
    include:
      - master

resources:
  repositories:
  - repository: imodel-native
    type: github
    endpoint: imodel-native
    name: iTwin/imodel-native

  - repository: imodel-native-internal
    type: github
    endpoint: imodel-native
    name: iTwin/imodel-native-internal

stages:
- stage: imodel_native_tests
  displayName: NodeAddon and iModelCore Tests
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Schedule', 'Manual', 'PullRequest'))

  jobs:
  - job: BuildAndRunTests
    timeoutInMinutes: 90

    workspace:
      clean: all

    pool:
      name: iModelTechCI
      demands: Agent.OS -equals Windows_NT

    variables:
      BB_V: 4
      BB_ARCH: x64
      PY_EXE: py -3
      BB_SRC_ROOT: $(Agent.BuildDirectory)/bbsrc
      bb: $(BB_SRC_ROOT)/BentleyBuild/BentleyBuild.py
      strategy: 'iModelCore;SkipPull_imodel-native-internal+iModelJsNodeAddon;SkipPull_imodel-native-internal'

    steps:
    - checkout: imodel-native
    - checkout: imodel-native-internal

    - task: PythonScript@0
      displayName: 'Get Branch Name'
      inputs:
        scriptSource: inline
        script: |
          import sys;
          if ( "System.PullRequest.SourceBranch" not in sys.argv[1] ):
            branchName = sys.argv[1];
          else:
            branchName = sys.argv[2];
          print ('##vso[task.setvariable variable=sourceBranch]' + branchName);
        arguments: '$(System.PullRequest.SourceBranch) $(Build.SourceBranchName)'

    - script: 'echo %sourceBranch%'
      displayName: 'Display Source Branch'

    - template: build/templates/prebuild.yml@imodel-native-internal
      parameters:
        otherRepo: imodel-native

    - script: $(PY_EXE) $(BB_SRC_ROOT)/imodel-native-internal/build/call_bb.py pull -v $(BB_V) -a $(BB_ARCH) -s $(strategy)
      displayName: Pull
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

    - script: |
        if not "%sourceBranch%" == "" (
          cd /d $(BB_SRC_ROOT)/BisSchemas
          git checkout %sourceBranch%
        )
      displayName: 'Set Source Branch'

    - script: |
        if not "%sourceBranch%" == "" (
          cd /d $(BB_SRC_ROOT)/BisSchemas
          git branch
        )
      displayName: 'Display Source Branch'

    - script: $(PY_EXE) $(bb) -v $(BB_V) -a $(BB_ARCH) -s $(strategy) build
      displayName: Build
