trigger:
  - master

pr:
  drafts: false
  branches:
    include:
      - master
  paths:
    exclude:
      - .github/CODEOWNERS
      - docs/

jobs:
- job: Validation
  workspace:
    clean: all

  pool:
    name: imodelNative-Debian12

  variables:
    - name: validationOut
      value: '$(Agent.BuildDirectory)/ValidationResults'
    - name: comparisonOut
      value: '$(Agent.BuildDirectory)/ComparisonResults'
    - name: imodelValidationOut
      value: '$(Agent.BuildDirectory)/IModelValidationResults'
    - name: jsonValidationOut
      value: '$(Agent.BuildDirectory)/JsonValidationResults'
    - name: schemaUpgradeValidationOut
      value: '$(Agent.BuildDirectory)/SchemaUpgradeValidationResults'

  steps:
  - task: NodeTool@0
    displayName: 'Install Node 22.x'
    inputs:
      versionSpec: 22.x
      checkLatest: true

  - checkout: self
    clean: true

  - task: CmdLine@2
    displayName: 'NPM Configuration'
    inputs:
      script: 'npm config list' 

  - script: npm install
    displayName: npm install

  - script: | 
      mkdir -p "$validationOut"
      echo "Schema Validation Output Dir= $validationOut"
    displayName: 'Create Validation Output Directory'

  - script: npm run validateSchemas -- --BisRoot . --OutDir $(validationOut)
    workingDirectory: 
    displayName: Perform BIS Schema Validation

  # - task: ArchiveFiles@2
  #   condition: succeededOrFailed()
  #   displayName: 'ArchiveFiles - Validation Results'
  #   inputs:
  #     rootFolderOrFile: $(validationOut) 
  #     includeRootFolder: false 
  #     archiveType: 7z
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/ValidationResults.zip' 
  #     replaceExistingArchive: true 

  # - publish: '$(Build.ArtifactStagingDirectory)/ValidationResults.zip'
  #   condition: succeededOrFailed()
  #   artifact: bis-schema-validation-logs-Attempt-$(System.JobAttempt)
  #   displayName: 'Publish BIS Schema Validation Results'

  - script: | 
      mkdir -p "$comparisonOut"
      echo "Schema Comparison Output Dir= $comparisonOut"
    condition: succeededOrFailed()
    displayName: 'Create Schema Comparison Output Directory'

  - script: npm run compareSchemas -- --BisRoot . --OutDir $(comparisonOut)
    workingDirectory: 
    condition: succeededOrFailed()
    displayName: Perform BIS Schema Comparison

  # - task: ArchiveFiles@2
  #   condition: succeededOrFailed()
  #   displayName: 'ArchiveFiles - Comparison Results'
  #   inputs:
  #     rootFolderOrFile: $(comparisonOut) 
  #     includeRootFolder: false 
  #     archiveType: 7z
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/ComparisonResults.zip' 
  #     replaceExistingArchive: true 

  # - publish: '$(Build.ArtifactStagingDirectory)/ComparisonResults.zip'
  #   condition: succeededOrFailed()  
  #   artifact: bis-schema-comparison-logs-Attempt-$(System.JobAttempt)
  #   displayName: 'Publish BIS Schema Comparison Results'

  - script: | 
      mkdir -p "$imodelValidationOut"
      echo "Schema Validation Output Dir= $imodelValidationOut"
    displayName: 'Create iModel Validation Output Directory'

  - script: npm run iModelSchemaValidation -- --released --OutDir $(imodelValidationOut)
    displayName: ValidateReleasedSchemas

  - script: npm run iModelSchemaValidation -- --wip --OutDir $(imodelValidationOut)
    displayName: ValidateWIPSchemas

  # - task: ArchiveFiles@2
  #   condition: succeededOrFailed()
  #   displayName: 'ArchiveFiles - iModel Validation Results'
  #   inputs:
  #     rootFolderOrFile: $(imodelValidationOut) 
  #     includeRootFolder: false 
  #     archiveType: 7z
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/IModelValidationResults.zip' 
  #     replaceExistingArchive: true 

  # - publish: '$(Build.ArtifactStagingDirectory)/IModelValidationResults.zip'
  #   condition: succeededOrFailed()  
  #   artifact: imodel-schema-validation-logs-Attempt-$(System.JobAttempt)
  #   displayName: 'Publish iModel Schema Validation Results'

  - script: | 
      mkdir -p "$schemaUpgradeValidationOut"
      echo "Schema Validation Output Dir= $schemaUpgradeValidationOut"
    displayName: 'Create Schema Upgrade Validation Output Directory'

  - script: npm run iModelSchemaValidation -- --schemaUpgradeTesting --OutDir $(schemaUpgradeValidationOut)
    displayName: Schema Upgrade Validation

  # - task: ArchiveFiles@2
  #   condition: succeededOrFailed()
  #   displayName: 'ArchiveFiles - Schema Upgrade Validation Results'
  #   inputs:
  #     rootFolderOrFile: $(schemaUpgradeValidationOut) 
  #     includeRootFolder: false 
  #     archiveType: 7z
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/SchemaUpgradeValidationResults.zip' 
  #     replaceExistingArchive: true 

  # - publish: '$(Build.ArtifactStagingDirectory)/SchemaUpgradeValidationResults.zip'
  #   condition: succeededOrFailed()  
  #   artifact: schema-upgrade-validation-logs-Attempt-$(System.JobAttempt)
  #   displayName: 'Publish Schema Upgrade Validation Results'

  - script: | 
      mkdir -p "$jsonValidationOut"
      echo "Schema JSON Validation Output Dir= $jsonValidationOut"
    condition: succeededOrFailed()
    displayName: 'Create Schema JSON Validation Output Directory'

  - script: npm run validateJsonSchemas -- --BisRoot . --OutDir $(jsonValidationOut)
    workingDirectory: 
    condition: succeededOrFailed()
    displayName: Perform BIS Schema JSON creation validation

  # - task: ArchiveFiles@2
  #   condition: succeededOrFailed()
  #   displayName: 'ArchiveFiles - Schema JSON Validation Results'
  #   inputs:
  #     rootFolderOrFile: $(jsonValidationOut) 
  #     includeRootFolder: false 
  #     archiveType: 7z
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/JsonValidationResults.zip' 
  #     replaceExistingArchive: true 

  # - publish: '$(Build.ArtifactStagingDirectory)/JsonValidationResults.zip'
  #   condition: succeededOrFailed()  
  #   artifact: bis-schema-json-validation-logs-Attempt-$(System.JobAttempt)
  #   displayName: 'Publish BIS Schema JSON Validation Results'

  - script: npm run iModelSchemaValidation -- --compareSnapshot
    displayName: Snapshot Comparison

  - script: npm run validateSchemaInventory
    displayName: Validate Schema Inventory

  - script: npm run iModelSchemaValidation -- --compareSnapshot
    displayName: Snapshot Comparison
