trigger:
  branches:
    include:
      - master
  paths:
    include:
      - tools/*

workspace:
  clean: all

pool:
  name: Hosted VS2017

variables:
  - group: 

steps:
- task: NodeTool@0
  displayName: 'Use Node 12.18.0'
  inputs:
    versionSpec: 12.18.0

- checkout: self
  clean: true

 
 
 
 
 
 
 
 
 
 
 

- task: CmdLine@2
  displayName: 'NPM CONFIGURATION'
  inputs:
    script: 'npm config list' 

- script: npm install
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Schema Package Generation Tests'
  inputs:
    command: custom
    customCommand: run testPkgGen

- task: Npm@1
  displayName: 'Schema Inventory Generation Tests'
  inputs:
    command: custom
    customCommand: run testInvGen

